### PR TITLE
Validators for name, password, birth Date and gender, also db models

### LINKED ISSUE #148: Write the Validation Check For Password
Using the validation library, create the model for passwords:

Passwords should:
- Be at least 8 characters long
- Be at most 15 characters long
- Contains only English characters, numbers or . _ *

### PR DESCRIPTION
**Pull request by berkatil**
Closes #148 #149 #151 #152

### CODE REVIEW

**Comment by fileames** [comment]
Everything looks fine. We did not discuss this but since we will be storing hashed passwords, should we include validation on model level or maybe check somewhere else?

**Comment by berkatil** [comment]
You are right, then what about checking it whenever we receive the request in the endpoint functions, if it passes the validation then we can create the model and then validate the rest?

**Comment by berkatil** [comment]
Or , probably, we validate the input in the endpoint function and then we call the class method to do the required operations. So, maybe we can leave it like this and in the class method we can hash the password and change the value of the object. What do you think?

**Comment by fileames** [comment]
> Or , probably, we validate the input in the endpoint function and then we call the class method to do the required operations. So, maybe we can leave it like this and in the class method we can hash the password and change the value of the object. What do you think?

Since these models will also be in the database, I think it would be better if don't leave it like this. We can do the check on the endpoint function I think since this field will be the only one that we will make separate validation. What do you think?

**Comment by berkatil** [comment]
sure, it makes sense

**Pull request merged**
