### PR TITLE
get recommendation endpoint and tests

### LINKED ISSUE #381: Implement GET endpoint for the recommendations
| path                               | type   | functionality                               | parameters                                                                                                                                                                                                                | example                                                                                                                                                                                                                                  |
|---------------------------------------------------------------|--------|---------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| recommentations | GET | get user recommended events |    |  |

For the recommendations, we plan to return events that is one of the following:
- Events with sports which the user has a added matching skill level.
- Events created by the users followed by the user.
- If user has a location entered, events that are close to the user. Meaning of close should be determined.

### PR DESCRIPTION
**Pull request by berkatil**
Closes #381

### CODE REVIEW

**Comment by fileames** [comment]
Maybe we can filter events that passed from recommendations. What do you think?

**Comment by berkatil** [comment]
> filter

sure it makes sense, thanks for this remark

**Comment by berkatil** [comment]
> > filter
> 
> sure it makes sense, thanks for this remark

done

**Comment by fileames** [comment]
Everything looks fine, thanks for the effort.

**Pull request merged**
